### ISSUE TITLE
New GreatFET doesn't show up in lsusb or dmesg

### ISSUE THREAD

**Issue by jedahan** [greatscottgadgets/greatfet-tutorials#13]
got a greatfet one from adafruit, plugged into my laptop but lsusb and dmesg doesn't show anything. I probably need to choose the correct kernel modules. Using a usb hub since i dont have an adapter that goes usb-c to micro usb.

What modules should I try loading?

**Comment by miek** [comment]
Which distro are you using?
You shouldn't need any special kernel modules and dmesg should show *something* either way.

Have you tried with different cables, and checked that other devices work on that hub?
Do any LEDs come on when it's plugged in, and how do they behave? Also, are you plugging into the correct side of the GreatFET (the convex side with the buttons & LEDs)?

**Comment by jedahan** [comment]
Tried with multiple usb cables on my linux laptop, running [k1ss](https://k1sslinux.org/). 

On a raspberry pi with no hub, running retropie, didn't show up in either lsusb or dmesg.

Plugged into windows 10 desktop, didn't see it show up using zadig in the list when choosing 'show all devices'.

All concave side of board, with usb-a to micro-usb cable.

**Comment by miek** [comment]
Could you try booting the GreatFET in DFU mode (by holding the DFU button while plugging it in) and see if it shows up?

**Comment by jedahan** [comment]
Held down DFU while plugging it in. `greatfet info` shows "No greatFET devices found", also no leds light up.

**Comment by miek** [comment]
Unfortunately it sounds like that GreatFET is faulty, if you contact Adafruit they'll arrange a replacement for you.
