### ISSUE TITLE
Document needs updating

### ISSUE THREAD

**Issue by RichardEWillis** [greatscottgadgets/greatfet-tutorials#16]
"Getting started"
The wget URL is no longer correct, the udev rule was moved some time in the past.

wget https://raw.githubusercontent.com/greatscottgadgets/greatfet/master/host/misc/
54-greatfet.rules

no longer works. The path should be changed to: 
https://raw.githubusercontent.com/greatscottgadgets/greatfet/master/host/util/
54-greatfet.rules

**Comment by antoinevg** [comment]
Fixed by: https://github.com/greatscottgadgets/greatfet-tutorials/pull/17
