### ISSUE TITLE
Windows setup

### ISSUE THREAD

**Issue by Alfatross** [greatscottgadgets/greatfet-tutorials#8]
I'm new to this whole thing with Micro-controllers but I went through the steps setting it up for windows even though I have be playing with it on Linux os however i installed the greatfet with the Zadig and this part I don't think is doing it's job because I am unable to communicate with the greatfet when i use the command "gf info" it just gives me a running list of statements I don't know how to read anyway it would be AWESOME! if you all put up video tutorials!

**Comment by straithe** [comment]
Thank you for the video tutorial suggestion! Can you please open an issue on the [GreatFET repository](https://github.com/greatscottgadgets/greatfet) so I can assist you further with your Zadig issue over there?

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
