### ISSUE TITLE
GPIO analog/digital pins

### ISSUE THREAD

**Issue by Alfatross** [greatscottgadgets/greatfet-tutorials#9]
New to Micro-controllers looked at arduino and raspberry pi for areas of competition but I chose the greatfet due to the vast amount of GPIO pins however I'm new to this and have no idea what I'm doing I have already turned on LEDs through the pins but what I would like to know is which ones can I use for analog VS digital pins I have wrote a the program using the other tutorial but since I'm new to even programming I don't know how to set up an instance to use classes for the pins for reasons listed above! I have been watching any videos on Youtube to see if these are even talked about but no such luck.....Video tutorials would be AWESOME!

**Comment by straithe** [comment]
Thank you for the tutorial suggestion! Can you please open an issue on the [GreatFET repository](https://github.com/greatscottgadgets/greatfet) so I can assist you further with the rest of your issue?

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
